# vim ft=yaml
# travis-ci.org and coveralls definition for PsychoPy tests
language: python
python:
  - "2.7"
env:
 matrix:
  - COVERAGE=1
virtualenv:
  system_site_packages: true
before_install:
  - ci/deb-install-build-depends
  - ci/deb-install-build-depends-pip
install:
  - flac -version
script:
  - ci/run-tests
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then coveralls; fi
