[project]
name = "psychopy"
description = "Psychology experiment software in Python"
classifiers = [
    "Development Status :: 4 - Beta",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10", ]
requires-python = ">=3.6"
dependencies = [
    "requests[security]",
    "future",
    "cryptography",
    "pypi_search",
    "numpy < 1.24.0",
    "scipy",
    "matplotlib",
    "pandas",
    "pillow",
    "soundfile >= 0.11.0",
    "python-bidi",
    "arabic_reshaper",
    "json_tricks",
    "xlrd", "openpyxl",
    "pyserial",
    "pyyaml",
    "gevent",
    "msgpack",
    "msgpack-numpy",
    "psutil",
    "tables",
    "pyzmq",
    "ujson",
    "moviepy",
    "opencv-python",
    "python-gitlab",
    "gitpython",
    "astunparse",
    "esprima",
    "freetype-py",
    "jedi >= 0.16",
    "psychtoolbox",
    "python-vlc == 3.0.11115; platform_system == \"Windows\"",
    "python-vlc >= 3.0.12118; platform_system != \"Windows\"",
    "javascripthon",
    "pyglet == 1.4.11; platform_system == \"Windows\"",
    "pyglet == 1.5.27; platform_system != \"Windows\"",
    "questplus >= 2019.3; python_version >= \"3.6\"",
    "imageio >= 2.5",
    "imageio-ffmpeg",
    "pyparallel; platform_system == \"Linux\"",
    "pyWinhook; platform_system == \"Windows\"",
    "pyqt5", "wxPython == 4.1.1; platform_system == \"Darwin\"",
    "wxPython >= 4.1.1; platform_system != \"Darwin\"",
    "pypiwin32; platform_system == \"Windows\"",
    "pyobjc-core < 8.0; platform_system == \"Darwin\"",
    "pyobjc-framework-Quartz < 8.0; platform_system == \"Darwin\"",
    "pyobjc < 8.0; platform_system == \"Darwin\"",
    "python-xlib; platform_system == \"Linux\"",
    "distro; platform_system == \"Linux\"",
    "websocket_client",
    "markdown-it-py",
    "ffpyplayer",
    "tobii-research; python_version <= \"3.8\"",
    "egi-pynetstation", ]
dynamic = ["version", ]

[[project.authors]]
name = "Open Science Tools Ltd"
email = "support@opensciencetools.org"

[[project.maintainers]]
email = "support@opensciencetools.org"

[project.license]
text = "GNU GPLv3 (or more recent equivalent)"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
Homepage = "https://www.psychopy.org/"
Download = "https://github.com/psychopy/psychopy/releases/"

[project.gui-scripts]
psychopy = "psychopy.app.psychopyApp:main"

[build-system]
requires = ["setuptools>=61.2", "distro; platform_system == \"Linux\"", ]
build-backend = "setuptools.build_meta"

[tool.setuptools]
license-files = ["LICENSE", ]
include-package-data = false

[tool.versioneer]
vcs = "git"
style = "pep440"
versionfile_source = "psychopy/_version.py"
versionfile_build = ""
tag_prefix = "''"

[tool.distutils.bdist_wheel]
universal = 1

[tool.psychopy]
src = ["psychopy"]