data_store: {enable: true}
monitor_devices:
- Display:
    default_eye_distance: {surface_center: 500, unit_type: mm}
    device_number: 0
    name: display
    physical_dimensions: {height: 340, unit_type: mm, width: 590}
    psychopy_monitor_name: default
    reporting_unit_type: pix
- Keyboard: {name: kb}
- Mouse: {name: mouse}
- Experiment: {name: experimentRuntime}
- eyetracker.hw.smi.iviewx.EyeTracker:
    calibration:
      auto_pace: true
      pacing_speed: FAST
      screen_background_color: 20
      show_validation_accuracy_window: true
      target_attributes: {target_color: 239, target_inner_color: RED, target_size: 30}
      target_type: CIRCLE_TARGET
      type: FIVE_POINTS
    device_timer: {interval: 0.002}
    enable: true
    event_buffer_length: 1024
    model_name: REDm
    monitor_event_types: [BinocularEyeSampleEvent, FixationStartEvent, FixationEndEvent]
    name: tracker
    network_settings: {receive_ip_address: 127.0.0.1, receive_port: 5555, send_ip_address: 127.0.0.1,
      send_port: 4444}
    runtime_settings:
      sample_filtering: {FILTER_ALL: FILTER_OFF}
      sampling_rate: 60
      track_eyes: BINOCULAR_AVERAGED
      vog_settings: {pupil_measure_types: PUPIL_DIAMETER}
    save_events: true
    stream_events: true
